### ISSUE TITLE
High CPU usage?

### ISSUE THREAD

**Issue by jiyinyiyong** [Flying-Toast/simple-websockets#11]
lack of sleep?

![image](https://user-images.githubusercontent.com/449224/140972808-445e90c3-e50f-4e98-a49d-f2095473d2f8.png)

**Comment by Flying-Toast** [comment]
I've fixed the example in https://github.com/Flying-Toast/simple-websockets/commit/e543bcd6d8c00fd08189411e767133e9b8251a98, could you take a look at the change and see if your code is doing the same thing? Please re-open the issue if you're still having issues.

**Comment by jiyinyiyong** [comment]
Looks good now, cheers~

![image](https://user-images.githubusercontent.com/449224/140979109-c479829d-1ca4-4f6e-9281-5dfb77c6b1d3.png)
