### ISSUE TITLE
Convert message to string

### ISSUE THREAD

**Issue by LittleRobertTables** [Flying-Toast/simple-websockets#14]
How do I convert a message back to a string. Thanks.

**Comment by LittleRobertTables** [comment]
```rs
let msg_str: &str =  message.into();
```
fails because " the trait `From<simple_websockets::Message>` is not implemented for `&str`"

**Comment by Flying-Toast** [comment]
You can use pattern matching. For instance:

```Rust
if let Message::Text(ref msg_str) = message {
    println!("{}", msg_str);
}
```

**Comment by Flying-Toast** [comment]
I'll mark this as resolved, feel free to re-open it if you have something else.

**Comment by LittleRobertTables** [comment]
Thanks! (I'm still very new to this language :))
