### ISSUE TITLE
Option for binding to port 0

### ISSUE THREAD

**Issue by stephan-moeller** [Flying-Toast/simple-websockets#16]
Hello

I am creating an application consisting of a udp endpoint as well as a websocket endpoint.

I would like to do full integration tests by spinning up my app with both endpoints listening and start sending stuff to the application and assert the result.

I would like all my tests to run as fast and reliably as possible.

The udp socket has the option to bind to port 0 which means, that the socket will be bound to any port available. Afterwards I am able to read the final port chosen, and I can start sending udp packets towards this port. Code:

let udp_socket: UdpSocket = std::net::UdpSocket::bind(&String::from("127.0.0.1:0")).unwrap();
let server_udp_endpoint: SocketAddr = udp_socket.local_addr().unwrap();

I am able to bind to port 0 as well in simple-websockets this way:

let websocket_event_hub: EventHub = simple_websockets::launch(0).unwrap();

But the problem is: I can't read the final port anywhere afterwards.

One solution could be creating an overload for launch(...) taking a tcpListener as input. This way I can start the listener myself, read the address and call launch(tcpListener), like this:

let my_listener: TcpListener = std::net::TcpListener::bind("").unwrap();
let final_addr: std::net::SocketAddr = my_listener.local_addr().unwrap()
let event_hub = simple_websockets::launch(my_listener);

Another option would be to have the local_addr() value fed back from the launch call and have it exposed on the EvenHub.

I am looking forward to hearing from you, as simple-websocket is so much nicer to work with than the alternatives outthere.

Thanks in advance!

**Comment by Flying-Toast** [comment]
Thanks for reporting this! I agree this would be a good feature to have, but I'm not sure I'll have much time to implement it in the near future. 

I'd be more than happy to review any PRs though, if you're interested in trying to implement it. Places of interest would be [here](https://github.com/Flying-Toast/simple-websockets/blob/7aa1b13159d329c3ad0ea59eb5f3f1255632f195/src/lib.rs#L210) and [here](https://github.com/Flying-Toast/simple-websockets/blob/7aa1b13159d329c3ad0ea59eb5f3f1255632f195/src/lib.rs#L222).

I like your idea of having an alternative launch function, e.g. `launch_with_listener(listener: TcpListener)`. Note that simple_websockets uses tokio under the hood, so the launch_with_listener function should take a std::net::TcpListener, and then call tokio's [`TcpListener::from_std`](https://docs.rs/tokio/1.25.0/tokio/net/struct.TcpListener.html#method.from_std) inside the function.

Let me know if you have any questions!

**Comment by SRYER** [comment]
I am looking into making an overload of launch with a std TcpListener as input. But what is the whole purpose of using the async functions when everything is started inside a std:thread (in the launch method) and calling start_runtime which is running async inside but wrapping everything in a clause which has then called .block_on(...) on it?

Could the repo maybe be simpler by just keep the spawned thread from the launch-function but then using the blocking std::net::TcpListener with blocking accept calls? I can try making a PR just to show you what I mean maybe? Not expecting you to accept, just as a base for discussion? :)

**Comment by Flying-Toast** [comment]
We can't use blocking accept calls, otherwise the concurrent websocket connections would not be able to run, as the non-async accept would block the entire thread and thus block any sending/receiving for already connected websockets.

block_on() runs the specified future but "blocks" in the sense that the call to block_on won't return until the future completes (which we want, because we don't want start_runtime() to immediately return). It doesn't block in the sense that other `.await`ed futures in the thread can still be run concurrently, as seen in the calls to `tokio::spawn` within the loop.
