### ISSUE TITLE
crates.io is oudated

### ISSUE THREAD

**Issue by antoKeinanen** [Flying-Toast/simple-websockets#24]
Hey! I was using this crate and I needed to clone  `Message`. I realized that there was no clone method on `Message` so I decided to check the repository source code but `Message` derives `clone` there. Then I checked the source stored in [docs.rs](https://docs.rs/crate/simple-websockets/latest/source/src/lib.rs) that cargo downloads and the struct `Message` did not derive clone. 

Any chance you could update the crates.io crate?

**Comment by Flying-Toast** [comment]
Done :)
